---
- name: Install and start Docker on Amazon Linux 2
  hosts: web
  become: yes

  tasks:
    - name: Update system packages
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Verify Docker version
      command: docker --version
      register: docker_version

    - name: Show Docker version
      debug:
        msg: "{{ docker_version.stdout }}"
